/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    '1. 地图初始化': typeof import('./src/components/1. 地图初始化.vue')['default']
    '10. 图元primit': typeof import('./src/components/10. 图元primit.vue')['default']
    '11. 3D瓦片': typeof import('./src/components/11. 3D瓦片.vue')['default']
    '12. 鼠标点击事件': typeof import('./src/components/12. 鼠标点击事件.vue')['default']
    '13. 鼠标移动事件': typeof import('./src/components/13. 鼠标移动事件.vue')['default']
    '14. 三维模型': typeof import('./src/components/14. 三维模型.vue')['default']
    '15. 粒子效果': typeof import('./src/components/15. 粒子效果.vue')['default']
    '16. 点聚合': typeof import('./src/components/16. 点聚合.vue')['default']
    '17. 练习---视角导航': typeof import('./src/components/17. 练习---视角导航.vue')['default']
    '18. 练习2': typeof import('./src/components/18. 练习2.vue')['default']
    '2. 地图控件': typeof import('./src/components/2. 地图控件.vue')['default']
    '3. 坐标转换': typeof import('./src/components/3. 坐标转换.vue')['default']
    '3D瓦片': typeof import('./src/components/11. 3D瓦片.vue')['default']
    '4. 相机': typeof import('./src/components/4. 相机.vue')['default']
    '5. 实体': typeof import('./src/components/5. 实体.vue')['default']
    '6. 组合式实体': typeof import('./src/components/6. 组合式实体.vue')['default']
    '7. 实体的删除': typeof import('./src/components/7. 实体的删除.vue')['default']
    '8. CallbackProperty动态实体': typeof import('./src/components/8. CallbackProperty动态实体.vue')['default']
    '9. 加载不同格式数据': typeof import('./src/components/9. 加载不同格式数据.vue')['default']
    '地图初始化': typeof import('./src/components/1. 地图初始化.vue')['default']
    '地图控件': typeof import('./src/components/2. 地图控件.vue')['default']
    '点聚合': typeof import('./src/components/16. 点聚合.vue')['default']
    '加载不同格式数据': typeof import('./src/components/9. 加载不同格式数据.vue')['default']
    '粒子效果': typeof import('./src/components/15. 粒子效果.vue')['default']
    '练习---视角导航': typeof import('./src/components/17. 练习---视角导航.vue')['default']
    '练习2': typeof import('./src/components/18. 练习2.vue')['default']
    '三维模型': typeof import('./src/components/14. 三维模型.vue')['default']
    '实体': typeof import('./src/components/5. 实体.vue')['default']
    '实体的删除': typeof import('./src/components/7. 实体的删除.vue')['default']
    '鼠标点击事件': typeof import('./src/components/12. 鼠标点击事件.vue')['default']
    '鼠标移动事件': typeof import('./src/components/13. 鼠标移动事件.vue')['default']
    '图元primit': typeof import('./src/components/10. 图元primit.vue')['default']
    '相机': typeof import('./src/components/4. 相机.vue')['default']
    '组合式实体': typeof import('./src/components/6. 组合式实体.vue')['default']
    '坐标转换': typeof import('./src/components/3. 坐标转换.vue')['default']
    App: typeof import('./src/components/App.vue')['default']
    'CallbackProperty动态实体': typeof import('./src/components/8. CallbackProperty动态实体.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
  }
}
